### ISSUE TITLE
Incompatibility between exchange categories addition in diagram and VP diagram styler

### ISSUE THREAD

**Issue by LisaF268** [eclipse-capella/capella#2061]
When VP diagram styler is active on a diagram, it is not possible to add exchange categories.

![Test model 1](https://user-images.githubusercontent.com/78154066/106177110-69083180-6198-11eb-9305-d92538f28686.PNG)
![Test model 2](https://user-images.githubusercontent.com/78154066/106177153-72919980-6198-11eb-9198-f3ccf980a545.PNG)
![No proposed exchange categories with VP diagram styler activated](https://user-images.githubusercontent.com/78154066/106177166-74f3f380-6198-11eb-8550-24d7baa6406f.PNG)
![proposed exchange categories when VP diagram styler is not activated](https://user-images.githubusercontent.com/78154066/106177183-79201100-6198-11eb-99ab-e228807f7ca4.PNG)

It is necessary to deactivate the viewpoint to add an exchange category on the diagram.

**Comment by SteveMonnier** [comment]
[Capella2061_exchange_category.zip](https://github.com/eclipse/capella/files/13371839/Capella2061_exchange_category.zip)
Steps to reproduce:
- Import the Capella project from the attached archive
- Open the existing LAB diagram
- Select "FunctionalExchange 1" and go to the properties view
- The field "Exchange category" should be empty. Select the "..." button
- On the "Transfer Dialog", double click on "ExchangeCategory1" to move it on the right side. Click on OK.
-> Validation: Check that "ExchangeCategory1" has been added to the field.

**Comment by pdulth** [comment]
Steps to reproduce:
- Create a PVMT model applied on Functional Exchange
![image](https://github.com/eclipse/capella/assets/34767327/79d65b0d-464b-4ad4-b2d0-9b52aae2ae66)
- Create an architecture blank diagram displaying an Functional Exchange
- Display Diagram Styler layer and color the exchange by applying the PVMT property value
- Create an Exchange Category on the Functional Exchange
- The Switch Exchange Category display an empty wizard if the Diagram Styler layer is enabled.

**Comment by SteveMonnier** [comment]
[Capella2061_exchange_category_v2.zip](https://github.com/eclipse-capella/capella/files/14566742/Capella2061_exchange_category_v2.zip)
I recreated my sample from Capella master branch and without requiring the VPMS viewpoint that wasn't needed in this context. 
@pdulth your changes adding some other calls to DiagramServices.getDiagramServices().isMapping looks good to me, thanks.

**Comment by SteveMonnier** [comment]
Hi @pdulth @tguiu, I noticed that Philippe's commit has been pushed but I missed that Etienne's 2 commits had not been merged as well. I rebase his 2 commits on the master branch and created this PR: https://github.com/eclipse-capella/capella/pull/2848
Thanks.

**Comment by pdulth** [comment]
Hi, Can you describe your validation scenario as for me it was ok with the fix. 
https://github.com/eclipse-capella/capella/issues/2061#issuecomment-1943728712

**Comment by SteveMonnier** [comment]
Hi, 
oh right, I should have added a link as it is "further up" in older messages of this issue: [this validation scenario](https://github.com/eclipse-capella/capella/issues/2061#issuecomment-1813726159) and the scenario migrated for Capella 7.x is in [a more recent comment](https://github.com/eclipse-capella/capella/issues/2061#issuecomment-1989983661).
Thanks @pdulth.

**Comment by roland-huber** [comment]
This problem also exists for Physical Link Categories.

**Comment by mPorhel** [comment]
Issue validated on FunctionalExchange with Version: 7.0.0 Build id: 202404171526

[2061_exchange_category_v3_diagramStyler_enabled.zip](https://github.com/eclipse-capella/capella/files/15066500/2061_exchange_category_v3_diagramStyler_enabled.zip)


![ValidationOnVersion-7 0 0-202404171526](https://github.com/eclipse-capella/capella/assets/1019672/7b0a7615-4cd2-46ba-b2e5-d3b10f25a301)


The patch proposed by Philippe is generic and deals with Sirius Mapping.
We have just tested with @SteveMonnier a few seconds ago with the addition of a Component Exchange Category in the provided sample + modification of the property scope. And  the Switch Component Exchange / Category works fine. 
It should be the same for Physical Link Exchange.

**Comment by SteveMonnier** [comment]
Hi. Indeed, we did some validation this morning and we found at that there had been an issue when I migrated the sample from 6.1 to 7.0. I migrated it again and it works with @pdulth commits. I abandonned the PR I created.
