### ISSUE TITLE
Use Edge as default browser on Windows

### ISSUE THREAD

**Issue by etraisnel2** [eclipse-capella/capella#2647]
As of Eclipse 2023-06, we need to use Edge as default web browser on Windows
see https://github.com/eclipse/kitalpha/issues/766

However, it is still required to force IE for richtext views
see https://github.com/eclipse/kitalpha/issues/764

**Comment by pdulth** [comment]
![image](https://github.com/eclipse/capella/assets/34767327/846499c5-0a5f-4986-a932-9979ba8e79a0)

**Comment by pdulth** [comment]
![image](https://github.com/eclipse/capella/assets/34767327/faa057b0-5dd5-4feb-a4ec-565800994655)

**Comment by etraisnel2** [comment]
In order to remove the feature that forces Richtext widgets to be rendered using IE, use the preference ForceIEOnRichTextWidgetWIN32 = false
