### ISSUE TITLE
Adding an accelerator allowing the concretization of a computed allocation.

### ISSUE THREAD

**Issue by ebausson-obeo** [eclipse-capella/capella#2714]
A "computed allocation" is displayed in the Semantic View for every not-leaf function whose ever leaf are allocated.
Add an accelerator automating such allocation for a given Function (circumstances allowing).

**Comment by SteveMonnier** [comment]
[Capella2714_CalculatedAllocationConcretization.zip](https://github.com/eclipse/capella/files/13395015/Capella2714_CalculatedAllocationConcretization.zip)
Steps to reproduce:
- Import the Capella project from the attached archive
- In the project explorer view, select the capella element "LogicalFunction 3.2" (located in "LogicalArchitecture/Logical Functions/Root Logical Function/Logical Function3)
- In the Semantic Browser, Referencing elements tab, you should see LC2 under the category "Allocating Actor/Component (computed)"
- Back in the project explorer view, from the selected "LogicalFunction 3.2" element.
- Validation#1: The contextual menu "Modeling accelerator" displays a 3rd option: "Concretize function allocation". Click on this accelerator.
- Change focus to a different LogicalFunction and select again "LogicalFunction 3.2"
- Validation#2: This time in the Semantic Browser, Referencing elements tab, you should see LC2 under the category "Allocating Actor/Component". The "(computed)" suffix is gone.

**Comment by lredor** [comment]
As said in PR #2791, `this feature is a specific need and will not be merged on the master branch`.
