### ISSUE TITLE
Update Tips and tricks documentation

### ISSUE THREAD

**Issue by lfasani** [eclipse-capella/capella#2803]
The aim is to update the Capella documentation to adapt and to highlight new features such as:
* new layout features (layout children, layout ports, "move pinned elements" ..)
* color management

**Comment by etraisnel2** [comment]
Seems like few links to deleted images were not properly cleaned up 
Can you fix it so the broken links junit passes ?
https://ci.eclipse.org/capella/job/capella-product/job/master/505/
